// nexus setup — interactive gateway config wizard.
// Prompts for base URL, API key, model; writes .env-gateway with mode 600.
// Non-interactive: `nexus setup --base=URL --key=KEY --model=NAME --yes`
// Zero deps. Node >= 22 ESM.

import { writeFileSync, writeSync, existsSync, chmodSync, statSync, readSync, openSync } from 'node:fs';
import { join } from 'node:path';

const DEFAULT_BASE = 'https://api.asynx6.tech/v1';
const DEFAULT_MODEL = 'hermes-agent';

/** Parse nexus setup argv. */
export function parseSetupArgs(argv) {
  const flags = {};
  const positional = [];
  for (const a of argv) {
    if (a.startsWith('--')) {
      const [k, ...rest] = a.slice(2).split('=');
      flags[k] = rest.length ? rest.join('=') : true;
    } else positional.push(a);
  }
  return { flags, positional };
}

function ask(q, def) {
  // Sync read from stdin fd 0 — keeps zero deps.
  const fd = 0;
  writeSync(1, `${q}${def ? ` [${def}]` : ''}: `);
  let line = '';
  const buf = Buffer.alloc(1);
  while (true) {
    const n = readSync(fd, buf, 0, 1, null);
    if (n === 0) break;
    const ch = buf.toString('utf8');
    if (ch === '\n' || ch === '\r') break;
    line += ch;
  }
  const v = line.trim();
  return v || (def ?? '');
}

/** Build .env-gateway content. */
export function buildEnvFile({ baseUrl, apiKey, models }) {
  return [
    '# NEXUS gateway config — generated by `nexus setup`',
    '# Secrets only. Behavioral settings live in config, not here.',
    `NEXUS_GATEWAY_BASE=${baseUrl}`,
    `NEXUS_GATEWAY_KEY=${apiKey}`,
    `NEXUS_GATEWAY_MODELS=${models}`,
    ''
  ].join('\n');
}

/**
 * Run the setup wizard.
 * @returns {number} exit code (0 ok, 2 bad input)
 */
export async function runSetup(argv, opts = {}) {
  const { flags } = parseSetupArgs(argv);
  const out = opts.stdout ?? console.log;
  const err = opts.stderr ?? console.error;
  const cwd = opts.cwd ?? process.cwd();
  const envPath = opts.envPath ?? join(cwd, '.env-gateway');

  // Non-interactive mode: all three from flags.
  const nonInteractive = flags.yes || flags.y;
  let baseUrl = flags.base ?? flags['base-url'];
  let apiKey = flags.key ?? flags.apikey ?? flags['api-key'];
  let models = flags.model ?? flags.models;

  if (nonInteractive) {
    baseUrl = baseUrl ?? DEFAULT_BASE;
    apiKey = apiKey ?? '';
    models = models ?? DEFAULT_MODEL;
    if (!apiKey) {
      err('nexus setup: --key is required in non-interactive mode');
      return 2;
    }
  } else {
    out('nexus setup — configure your AI gateway');
    out('');
    baseUrl = ask('Gateway base URL', baseUrl ?? DEFAULT_BASE);
    apiKey = ask('API key', apiKey);
    models = ask('Model (comma-separated for multiple)', models ?? DEFAULT_MODEL);
    out('');
  }

  if (!baseUrl || !apiKey) {
    err('nexus setup: base URL and API key are required');
    return 2;
  }

  const content = buildEnvFile({ baseUrl, apiKey, models });
  writeFileSync(envPath, content, { mode: 0o600 });

  // Best-effort chmod on POSIX; no-op on Windows.
  try {
    if (process.platform !== 'win32') chmodSync(envPath, 0o600);
  } catch { /* best-effort */ }

  const mode = (() => { try { return statSync(envPath).mode; } catch { return 0; } })();
  out(`Wrote ${envPath} (mode ${mode.toString(8)})`);
  out(`  base   = ${baseUrl}`);
  out(`  model  = ${models}`);
  out('Run `nexus doctor` to verify the connection.');
  return 0;
}
